### ISSUE TITLE
[Problem] Text frame aggregation disabled

### ISSUE THREAD

**Issue by Atsyn** [knowledgecode/WebSocket-for-Android#21]
When we use this plugin we have a problem.
Socket closed with error code **1008** and message **Text frame aggregation disabled**.

Can you describe how can be fix or resolve it.

Yes, we can crop data but we want get it without cropping.

**Comment by knowledgecode** [comment]
Thank you for using this plugin and reporting the issue. I've figured out what causes the error and fixed it. That test version is now push on a develop branch. Could you try it out? If will be resolved the error, will publish it as ver 0.8.1.

In order to try it out, need to remove it and install the test version on a develop branch:
```shell
$ cordova plugin remove com.knowledgecode.cordova.websocket
$ cordova plugin add https://github.com/knowledgecode/WebSocket-for-Android#develop

**Comment by Atsyn** [comment]
Did not help.
We can send only 8192 bites.

**Comment by Atsyn** [comment]
Did not help.
We can send only 8192 bites.

**Comment by knowledgecode** [comment]
Hm...
We could have certainly sent only 8192 bytes by using the master version, but the develop branch version has been probably fixed. Make sure whether you installed the develop branch version. I additionally pushed updating to the branch to update version of the plugin a little ago. If you succeed installing the new version, you can see the display as follows:

```shell
$ cordova plugin
com.knowledgecode.cordova.websocket 0.8.1 "WebSocket for Android"

**Comment by knowledgecode** [comment]
I decide to publish the new version formally though your response is nothing because I believe that this bug is already fixed. And then I will close this issue once, but if you think it is not resolved, please post a message again here.
If it weren't for your report, I wouldn't notice it. Thank you very much.
